services:
  - type: web
    name: kuntau-pay
    plan: free
    runtime: node
    buildCommand: npm install --include=dev && npm run web:build
    startCommand: node server/prisma/prepare.js && npx prisma db push --schema=server/prisma/schema.prisma && node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: kuntau-pay-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: kuntau-pay-db
    plan: free
